In [2]:
def dictionarykeyfile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key

In [3]:
keyfile= "DataFiles/keypath.txt"
key = dictionarykeyfile(keyfile)
print(key)
evenkeys={item for item in key.items() if int(item[0])%2==0} #return set
print(evenkeys)

evenkeys={item for item in key}
print(evenkeys)

{'0': '4', '1': '5', '2': '6', '3': '7', '4': '8', '5': '9', '6': '0', '7': '1', '8': '2', '9': '3'}
{('6', '0'), ('8', '2'), ('2', '6'), ('0', '4'), ('4', '8')}
{'1', '7', '6', '0', '8', '2', '5', '9', '4', '3'}


### Numpy Library
 - Processing N-Dimentional Arrays

In [17]:
import numpy as np

li=[1,2,3,'z']
a= np.array(li)
print(a)
print(type(a))
a
b= np.arange(15)
b

['1' '2' '3' 'z']
<class 'numpy.ndarray'>


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
multilist1 = np.random.randint(0,100,size=6)#size=no. of elements in list
print(multilist1)

multilist2 = np.random.randint(0,100,size=(3,4))#size=no. of elements in list,no. of sublists
print(multilist2)

multilist3 = np.random.randint(0,100,size=(3,4,4))#size=no. of elements in list,no. of sublists,no. of multi lists 
print(multilist3,end='')

[84 23 11 43 76 46]
[[90 30 48 78]
 [92  3 32 59]
 [90  3 44 51]]
[[[78 25 64 17]
  [82 34 96 47]
  [31 63 50 30]
  [76 79 31 18]]

 [[32 14 72 11]
  [ 6 56 57 43]
  [18 56 17 90]
  [66 11 71 98]]

 [[38 18  1  5]
  [76 23 85 30]
  [81 95 52 60]
  [79  3 94 42]]]

In [39]:
multilist1[0]

multilist2[0][1]

multilist3[1][1][2]


57

In [42]:
print(multilist3.dtype)
print(multilist3.size)
print(multilist3.ndim)
print(multilist3.itemsize)
print(multilist3.nbytes)

int32
48
3
4
192


In [52]:
b.reshape(5,3)# convert single line list to multi line list
np.concatenate([a,b])  # combind multiple lists to single list
np.concatenate([a,b,multilist1])  # combind multiple lists to single list
np.concatenate([a,b],axis=1)  # combind multiple lists to single list, axis=1 then coloumns are constant

array(['1', '2', '3', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', '10', '11', '12', '13', '14', '84', '23', '11', '43', '76',
       '46'], dtype='<U11')

## Pandas
- Data Cleaning
- Data Transformation
- Data Analysis

### Notations
- Series
- DataFrames

In [61]:
import pandas as pd
print(pd)

internal1 = {'s1':21,"s2":18,"s3":24}

internal1 = pd.Series(internal1)
internal1

internal2 = {'s1':156,"s2":38,"s3":33}

internal2 = pd.Series(internal2)
internal2

final ={'internal1':internal1,'internal2':internal2}
final = pd.DataFrame(final)
print(final)
final


<module 'pandas' from 'C:\\Users\\IIIT-rgukt\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>
    internal1  internal2
s1         21        156
s2         18         38
s3         24         33


internal1  internal2
s1         21        156
s2         18         38
s3         24         33

In [62]:
final.columns # Names of all Colums

Index(['internal1', 'internal2'], dtype='object')

In [64]:
final.values # lists of all rows

array([[ 21, 156],
       [ 18,  38],
       [ 24,  33]], dtype=int64)

In [65]:
final.values[2]

array([24, 33], dtype=int64)

In [66]:
final.values[2][0]

24

In [67]:
final.values[2,0]

24

In [68]:
for row in final.values:
    print("internal1-",row[0],"internal2-",row[1])

internal1- 21 internal2- 156
internal1- 18 internal2- 38
internal1- 24 internal2- 33


In [70]:
final.loc[3]=[15,18]
final

internal1  internal2
s1         21        156
s2         18         38
s3         24         33
3          15         18

In [72]:
final.loc[1]=[12,33]
final

internal1  internal2
s1         21        156
s2         18         38
s3         24         33
3          15         18
1          12         33

In [81]:
final=final.drop(1)
final

internal1  internal2
s2         18         38
s3         24         33
3          15         18

In [84]:
final.values[1] = [1111,1111] # change values in multi dimentional list using column 
final

internal1  internal2
s2         18         38
s3       1111       1111
3           1          1

In [86]:
import pandas as pd
filepath="DataFiles/income.csv"
incomedf= pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [93]:
# Extract income 2013 
incomedf.values[-1,-1]
incomedf.values[-1][-1]
for row in incomedf.values:
    print(row[1],":",row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [97]:
# average income of particular state

sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [105]:
incomedf('Alaska')

TypeError: 'DataFrame' object is not callable

In [102]:
print(dir(incomedf),end='')


['GEOID', 'State', 'T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__r

In [107]:
# Average income of al states in year

sum=0
for row in incomedf.values:
    sum+=row[-2]
sum/len(incomedf.values)

50038.8